### ISSUE TITLE
Support and Feedback

### ISSUE THREAD

**Issue by github-netspective-admin** [strategy-coach/expectations-outcomes-hub-theme-jan-2025#39]
### Feedback Details
```yaml
name: Rejina KP
email: rejina.kp@citrusinformatics.com
subject: Support and Feedback
message: This is test message please ignore
submissionDate: 2025-05-14T09:03:09.063Z
pageUrl: https://demo.hub.opsfolio.com/#
```
